//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Palette.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public int CommentID { get; set; }
        public int CommenterID { get; set; }
        public int PostID { get; set; }
        public string CommentText { get; set; }
        public System.DateTime CommentedDate { get; set; }
    
        public virtual Posts Posts { get; set; }
        public virtual Users Users { get; set; }
    }
}
