//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Palette.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FollowingRelationsgips
    {
        public int FollowingRelationshipsID { get; set; }
        public int UserID { get; set; }
        public int FollowingID { get; set; }
        public System.DateTime FollowedDate { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
