//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Palette.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostColors
    {
        public int PostColorID { get; set; }
        public int PostID { get; set; }
        public int ColorHEX1 { get; set; }
        public int ColorHEX2 { get; set; }
        public int ColorHEX3 { get; set; }
    
        public virtual Posts Posts { get; set; }
    }
}
